# Generated by Django 4.2.5 on 2024-02-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query_optimization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productatrribute',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='query_optimization.attribute'),
        ),
    ]
