# Generated by Django 4.2.5 on 2023-09-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0002_rename_messahe_animal_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='message',
        ),
        migrations.AddField(
            model_name='animal',
            name='sound',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
